plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

def INCLUDE_OTHER_ARCHS = "true".equalsIgnoreCase(project.findProperty("includeOtherArchs"))
def isInGHA = System.getenv("GITHUB_ACTIONS") == "true"

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    mavenCentral()
}

def gitCommitHash = { ->
    try {
        ExecOutput result = providers.exec {
            commandLine = ['git', 'rev-parse', 'HEAD']
            ignoreExitValue = true
        }

        if (result.getResult().get().getExitValue() != 0) {
            return "<UnknownCommit>";
        } else {
            return result.standardOutput.asText.get().strip();
        }
    } catch (Exception e) {
        e.printStackTrace()
        return "<UnknownCommit>";
    }
}

def buildtime = {System.currentTimeSeconds()}

loom {
    // accessWidenerPath = file("src/main/resources/voxy.accesswidener")
    // Forge uses access transformers
    accessWidenerPath = file("src/main/resources/voxy.accesswidener") // Architectury Loom can actually convert AWs to ATs automatically!
    
    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
        
        mixinConfig "common.voxy.mixins.json"
        mixinConfig "client.voxy.mixins.json"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    // Embeddium (Forge's Sodium)
    modImplementation "maven.modrinth:embeddium:${project.embeddium_version}"

    // Oculus (Forge's Iris)
    // modImplementation "maven.modrinth:oculus:${project.oculus_version}"

    include(implementation("me.cortex:dummyprovider:0.0.0"))

    // Native dependencies
    def lgwjlVersion = "3.4.1"
    implementation platform("org.lwjgl:lwjgl-bom:$lgwjlVersion")

    implementation "org.lwjgl:lwjgl"
    forgeRuntimeLibrary(implementation("org.lwjgl:lwjgl-lmdb"))
    forgeRuntimeLibrary(implementation("org.lwjgl:lwjgl-zstd"))
    
    runtimeOnly "org.lwjgl:lwjgl:$lgwjlVersion:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl:$lgwjlVersion:natives-linux"
    forgeRuntimeLibrary(runtimeOnly("org.lwjgl:lwjgl-lmdb:$lgwjlVersion:natives-windows"))
    forgeRuntimeLibrary(runtimeOnly("org.lwjgl:lwjgl-zstd:$lgwjlVersion:natives-windows"))
    forgeRuntimeLibrary(runtimeOnly("org.lwjgl:lwjgl-lmdb:$lgwjlVersion:natives-linux"))
    forgeRuntimeLibrary(runtimeOnly("org.lwjgl:lwjgl-zstd:$lgwjlVersion:natives-linux"))

    forgeRuntimeLibrary(implementation('redis.clients:jedis:5.1.0'))
    forgeRuntimeLibrary(implementation('org.rocksdb:rocksdbjni:10.2.1'))
    forgeRuntimeLibrary(implementation('org.apache.commons:commons-pool2:2.12.0'))
    forgeRuntimeLibrary(implementation('org.lz4:lz4-java:1.8.0'))
    forgeRuntimeLibrary(implementation('org.tukaani:xz:1.10'))
    forgeRuntimeLibrary(implementation('org.xerial:sqlite-jdbc:3.49.1.0'))
}

def targetJavaVersion = 17 // Forge 1.20.1 requires Java 17 minimum
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
    it.options.deprecation = true
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}"}
    }
    if (!isInGHA) {
        def hash = gitCommitHash();
        if (!hash.equals("<UnknownCommit>")) {
            archiveClassifier.set(hash.substring(0,7));
        }
    }
}