modLoader="javafml"
loaderVersion="[47,)"
license="All-Rights-Reserved"
issueTrackerURL=""

[[mods]]
modId="voxy"
version="${file.jarVersion}"
displayName="Voxy"
logoFile="assets/voxy/icon.png"
authors="Cortex"
description="Far distance rendering mod utilising LoDs"

[[dependencies.voxy]]
modId="forge"
mandatory=true
versionRange="[47.4.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="client.voxy.mixins.json"

[[mixins]]
config="common.voxy.mixins.json"
